# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_auth_client.api.tsigkey_api import TsigkeyApi


class TestTsigkeyApi(unittest.TestCase):
    """TsigkeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TsigkeyApi()

    def tearDown(self) -> None:
        pass

    def test_create_tsig_key(self) -> None:
        """Test case for create_tsig_key

        Add a TSIG key
        """
        pass

    def test_delete_tsig_key(self) -> None:
        """Test case for delete_tsig_key

        Delete the TSIGKey with tsigkey_id
        """
        pass

    def test_get_tsig_key(self) -> None:
        """Test case for get_tsig_key

        Get a specific TSIGKeys on the server, including the actual key
        """
        pass

    def test_list_tsig_keys(self) -> None:
        """Test case for list_tsig_keys

        Get all TSIGKeys on the server, except the actual key
        """
        pass

    def test_put_tsig_key(self) -> None:
        """Test case for put_tsig_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
