# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_auth_client.models.zone import Zone

class TestZone(unittest.TestCase):
    """Zone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Zone:
        """Test Zone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Zone`
        """
        model = Zone()
        if include_optional:
            return Zone(
                account = '',
                api_rectify = True,
                catalog = '',
                dnssec = True,
                edited_serial = 56,
                id = '',
                kind = 'Native',
                master_tsig_key_ids = [
                    ''
                    ],
                masters = [
                    ''
                    ],
                name = '',
                nameservers = [
                    ''
                    ],
                notified_serial = 56,
                nsec3narrow = True,
                nsec3param = '',
                presigned = True,
                rrsets = [
                    pdns_auth_client.models.rr_set.RRSet(
                        changetype = '', 
                        comments = [
                            pdns_auth_client.models.comment.Comment(
                                account = '', 
                                content = '', 
                                modified_at = 56, )
                            ], 
                        name = '', 
                        records = [
                            pdns_auth_client.models.record.Record(
                                content = '', 
                                disabled = True, )
                            ], 
                        ttl = 56, 
                        type = '', )
                    ],
                serial = 56,
                slave_tsig_key_ids = [
                    ''
                    ],
                soa_edit = '',
                soa_edit_api = '',
                type = '',
                url = '',
                zone = ''
            )
        else:
            return Zone(
        )
        """

    def testZone(self):
        """Test Zone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
