# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_auth_client.models.get_stats200_response_inner import GetStats200ResponseInner

class TestGetStats200ResponseInner(unittest.TestCase):
    """GetStats200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStats200ResponseInner:
        """Test GetStats200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStats200ResponseInner`
        """
        model = GetStats200ResponseInner()
        if include_optional:
            return GetStats200ResponseInner(
                name = '',
                type = '',
                value = [
                    pdns_auth_client.models.simple_statistic_item.SimpleStatisticItem(
                        name = '', )
                    ],
                size = 56
            )
        else:
            return GetStats200ResponseInner(
        )
        """

    def testGetStats200ResponseInner(self):
        """Test GetStats200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
