# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_auth_client.api.autoprimary_api import AutoprimaryApi


class TestAutoprimaryApi(unittest.TestCase):
    """AutoprimaryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutoprimaryApi()

    def tearDown(self) -> None:
        pass

    def test_create_autoprimary(self) -> None:
        """Test case for create_autoprimary

        Add an autoprimary
        """
        pass

    def test_delete_autoprimary(self) -> None:
        """Test case for delete_autoprimary

        Delete the autoprimary entry
        """
        pass

    def test_get_autoprimaries(self) -> None:
        """Test case for get_autoprimaries

        Get a list of autoprimaries
        """
        pass


if __name__ == '__main__':
    unittest.main()
