# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_auth_client.models.ring_statistic_item import RingStatisticItem

class TestRingStatisticItem(unittest.TestCase):
    """RingStatisticItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RingStatisticItem:
        """Test RingStatisticItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RingStatisticItem`
        """
        model = RingStatisticItem()
        if include_optional:
            return RingStatisticItem(
                name = '',
                size = 56,
                type = '',
                value = [
                    pdns_auth_client.models.simple_statistic_item.SimpleStatisticItem(
                        name = '', 
                        value = '', )
                    ]
            )
        else:
            return RingStatisticItem(
        )
        """

    def testRingStatisticItem(self):
        """Test RingStatisticItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
