# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pdns_auth_client.models.tsig_key import TSIGKey

class TestTSIGKey(unittest.TestCase):
    """TSIGKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TSIGKey:
        """Test TSIGKey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TSIGKey`
        """
        model = TSIGKey()
        if include_optional:
            return TSIGKey(
                algorithm = '',
                id = '',
                key = '',
                name = '',
                type = ''
            )
        else:
            return TSIGKey(
        )
        """

    def testTSIGKey(self):
        """Test TSIGKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
