# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from pdns_auth_client.models.map_statistic_item import MapStatisticItem
from pdns_auth_client.models.ring_statistic_item import RingStatisticItem
from pdns_auth_client.models.statistic_item import StatisticItem
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

GETSTATS200RESPONSEINNER_ANY_OF_SCHEMAS = ["MapStatisticItem", "RingStatisticItem", "StatisticItem"]

class GetStats200ResponseInner(BaseModel):
    """
    GetStats200ResponseInner
    """

    # data type: StatisticItem
    anyof_schema_1_validator: Optional[StatisticItem] = None
    # data type: MapStatisticItem
    anyof_schema_2_validator: Optional[MapStatisticItem] = None
    # data type: RingStatisticItem
    anyof_schema_3_validator: Optional[RingStatisticItem] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[MapStatisticItem, RingStatisticItem, StatisticItem]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "MapStatisticItem", "RingStatisticItem", "StatisticItem" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = GetStats200ResponseInner.model_construct()
        error_messages = []
        # validate data type: StatisticItem
        if not isinstance(v, StatisticItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StatisticItem`")
        else:
            return v

        # validate data type: MapStatisticItem
        if not isinstance(v, MapStatisticItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MapStatisticItem`")
        else:
            return v

        # validate data type: RingStatisticItem
        if not isinstance(v, RingStatisticItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RingStatisticItem`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in GetStats200ResponseInner with anyOf schemas: MapStatisticItem, RingStatisticItem, StatisticItem. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[StatisticItem] = None
        try:
            instance.actual_instance = StatisticItem.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[MapStatisticItem] = None
        try:
            instance.actual_instance = MapStatisticItem.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[RingStatisticItem] = None
        try:
            instance.actual_instance = RingStatisticItem.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GetStats200ResponseInner with anyOf schemas: MapStatisticItem, RingStatisticItem, StatisticItem. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], MapStatisticItem, RingStatisticItem, StatisticItem]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


